name: claude_dart_flutter
description: Enables an idiomatic Dart api for Anthropic LLM's. For Dart and Flutter apps
version: 1.0.0
repository: https://github.com/malengatiger/claude_dart_flutter

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  dio: ^5.4.1
  json_annotation: ^4.8.1
  http: ^1.2.1

dev_dependencies:
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  lints: ^3.0.0
  test: ^1.25.2
